// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/VadimOcLock/metrics-service/internal/entity"
	metricservice "github.com/VadimOcLock/metrics-service/internal/service/metricservice"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// FindAllMetrics provides a mock function with given fields: ctx, arg
func (_m *Store) FindAllMetrics(ctx context.Context, arg metricservice.FindAllMetricsNewParams) ([]entity.Metrics, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindAllMetrics")
	}

	var r0 []entity.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindAllMetricsNewParams) ([]entity.Metrics, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindAllMetricsNewParams) []entity.Metrics); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.FindAllMetricsNewParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCounterMetrics provides a mock function with given fields: ctx, arg
func (_m *Store) FindCounterMetrics(ctx context.Context, arg metricservice.FindCounterMetricParams) (entity.Metrics, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindCounterMetrics")
	}

	var r0 entity.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindCounterMetricParams) (entity.Metrics, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindCounterMetricParams) entity.Metrics); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(entity.Metrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.FindCounterMetricParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindGaugeMetrics provides a mock function with given fields: ctx, arg
func (_m *Store) FindGaugeMetrics(ctx context.Context, arg metricservice.FindGaugeMetricParams) (entity.Metrics, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindGaugeMetrics")
	}

	var r0 entity.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindGaugeMetricParams) (entity.Metrics, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindGaugeMetricParams) entity.Metrics); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(entity.Metrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.FindGaugeMetricParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMetricsBatchTx provides a mock function with given fields: ctx, arg
func (_m *Store) UpdateMetricsBatchTx(ctx context.Context, arg metricservice.UpdateMetricsBatchTxParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetricsBatchTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpdateMetricsBatchTxParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertCounterMetric provides a mock function with given fields: ctx, arg
func (_m *Store) UpsertCounterMetric(ctx context.Context, arg metricservice.UpsertCounterMetricParams) (bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCounterMetric")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpsertCounterMetricParams) (bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpsertCounterMetricParams) bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.UpsertCounterMetricParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertGaugeMetric provides a mock function with given fields: ctx, arg
func (_m *Store) UpsertGaugeMetric(ctx context.Context, arg metricservice.UpsertGaugeMetricParams) (bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGaugeMetric")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpsertGaugeMetricParams) (bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpsertGaugeMetricParams) bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.UpsertGaugeMetricParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
