// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "github.com/VadimOcLock/metrics-service/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// HTMLBuilder is an autogenerated mock type for the HTMLBuilder type
type HTMLBuilder struct {
	mock.Mock
}

// BuildHTML provides a mock function with given fields: metrics
func (_m *HTMLBuilder) BuildHTML(metrics []entity.Metrics) (string, error) {
	ret := _m.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for BuildHTML")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]entity.Metrics) (string, error)); ok {
		return rf(metrics)
	}
	if rf, ok := ret.Get(0).(func([]entity.Metrics) string); ok {
		r0 = rf(metrics)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]entity.Metrics) error); ok {
		r1 = rf(metrics)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHTMLBuilder creates a new instance of HTMLBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTMLBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTMLBuilder {
	mock := &HTMLBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
