// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/VadimOcLock/metrics-service/internal/entity"
	metricservice "github.com/VadimOcLock/metrics-service/internal/service/metricservice"

	mock "github.com/stretchr/testify/mock"
)

// MetricService is an autogenerated mock type for the MetricService type
type MetricService struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, dto
func (_m *MetricService) Find(ctx context.Context, dto metricservice.FindDTO) (entity.Metrics, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 entity.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindDTO) (entity.Metrics, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindDTO) entity.Metrics); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(entity.Metrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.FindDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, dto
func (_m *MetricService) FindAll(ctx context.Context, dto metricservice.FindAllDTO) ([]entity.Metrics, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithHTML")
	}

	var r0 []entity.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindAllDTO) ([]entity.Metrics, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.FindAllDTO) []entity.Metrics); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metricservice.FindAllDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBatch provides a mock function with given fields: ctx, dto
func (_m *MetricService) UpdateBatch(ctx context.Context, dto metricservice.UpdateBatchDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpdateBatchDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCounter provides a mock function with given fields: ctx, dto
func (_m *MetricService) UpdateCounter(ctx context.Context, dto metricservice.UpdateCounterDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpdateCounterDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGauge provides a mock function with given fields: ctx, dto
func (_m *MetricService) UpdateGauge(ctx context.Context, dto metricservice.UpdateGaugeDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metricservice.UpdateGaugeDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricService creates a new instance of MetricService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricService {
	mock := &MetricService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
