package enum

const (
	GaugeMetricType   = "gauge"
	CounterMetricType = "counter"

	AllocMetricName         = "Alloc"
	BuckHashSysMetricName   = "BuckHashSys"
	FreesMetricName         = "Frees"
	GCCPUFractionMetricName = "GCCPUFraction"
	GCSysMetricName         = "GCSys"
	HeapAllocMetricName     = "HeapAlloc"
	HeapIdleMetricName      = "HeapIdle"
	HeapInuseMetricName     = "HeapInuse"
	HeapObjectsMetricName   = "HeapObjects"
	HeapReleasedMetricName  = "HeapReleased"
	HeapSysMetricName       = "HeapSys"
	LastGCMetricName        = "LastGC"
	LookupsMetricName       = "Lookups"
	MCacheInuseMetricName   = "MCacheInuse"
	MCacheSysMetricName     = "MCacheSys"
	MSpanInuseMetricName    = "MSpanInuse"
	MSpanSysMetricName      = "MSpanSys"
	MallocsMetricName       = "Mallocs"
	NextGCMetricName        = "NextGC"
	NumForcedGCMetricName   = "NumForcedGC"
	NumGCMetricName         = "NumGC"
	OtherSysMetricName      = "OtherSys"
	PauseTotalNsMetricName  = "PauseTotalNs"
	StackInuseMetricName    = "StackInuse"
	StackSysMetricName      = "StackSys"
	SysMetricName           = "Sys"
	TotalAllocMetricName    = "TotalAlloc"
	PollCountMetricName     = "PollCount"
	RandomValueMetricName   = "RandomValue"
)
